apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-webapp-deployment
  labels:
    app: hello-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-webapp
  template:
    metadata:
      labels:
        app: hello-webapp
    spec:
      containers:
      - name: hello-webapp
        image: blurdel/jenkins-hello:1.0.1
        ports:
        - containerPort: 8080
        # args:
        # - liveness
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-webapp-service
spec:
  type: NodePort
  selector:
    app: hello-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30111
