apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      # nodePort: {{ .Values.service.nodePort }}
