# Default values for the deployment
global:
  appPort: &appPort 8080

replicas: 1
image:
  repository: localhost:5000/jenkins-hello-world
  version: 1.0.5
  pullPolicy: IfNotPresent

podLabels:
  "nodeType": "swit"

ingress:
  host: hello.local
  # issuerName: hello-ingress
  # tlsSecret: hello-tls-data

service:
  type: ClusterIP
  port: *appPort
  targetPort: *appPort

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2
  successThreshold: 1
startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1